INFO:werkzeug: * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [09/Aug/2020 11:24:44] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Aug/2020 11:24:53] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Aug/2020 11:25:01] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Aug/2020 11:25:16] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Aug/2020 11:25:18] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [09/Aug/2020 11:28:19] "[37mGET / HTTP/1.1[0m" 200 -
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x00\x1a'
DEBUG:PIL.TiffImagePlugin:tag: ColorSpace (40961) - type: short (3) - value: b'\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: PixelXDimension (40962) - type: long (4) - value: b'\x00\x00\x05\x00'
DEBUG:PIL.TiffImagePlugin:tag: PixelYDimension (40963) - type: long (4) - value: b'\x00\x00\x03\x88'
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'\x00\x00\x00\x1a'
DEBUG:PIL.TiffImagePlugin:tag: ColorSpace (40961) - type: short (3) - value: b'\x00\x01'
DEBUG:PIL.TiffImagePlugin:tag: PixelXDimension (40962) - type: long (4) - value: b'\x00\x00\x05\x00'
DEBUG:PIL.TiffImagePlugin:tag: PixelYDimension (40963) - type: long (4) - value: b'\x00\x00\x03\x88'
INFO:werkzeug:127.0.0.1 - - [09/Aug/2020 11:28:34] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:01:17] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\ketan\Downloads\certificate_generator-master\app.py", line 55, in upload_files
    unsigned_image.save(temp_file_name)
  File "C:\Python\Python37\lib\site-packages\PIL\Image.py", line 2131, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/signed_certificate.jpg'
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:01:37] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:04:10] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:04:37] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:05:56] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:06:26] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\ketan\Downloads\certificate_generator-master\app.py", line 72, in home
    return render_template('index.html')
  File "C:\Python\Python37\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Python\Python37\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\Python37\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Python\Python37\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Python\Python37\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\Python37\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\Python37\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:08:08] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\ketan\Downloads\certificate_generator-master\app.py", line 72, in home
    return render_template('index.html')
  File "C:\Python\Python37\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Python\Python37\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\Python37\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Python\Python37\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Python\Python37\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\Python37\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\Python37\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:08:23] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:09:07] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:09:07] "[33mGET /images/sun-2297961_1920.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:09:25] "[33mPOST /handler.php HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:12:09] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:12:09] "[33mGET /sun.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:12:32] "[31m[1mPOST / HTTP/1.1[0m" 405 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:16:27] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:16:27] "[33mGET /sun.jpg HTTP/1.1[0m" 404 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\ketan\Downloads\certificate_generator-master\app.py", line 57, in upload_files
    send_mail(name, email)
  File "c:\Users\ketan\Downloads\certificate_generator-master\app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 882, in sendmail
    (code, resp) = self.data(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 560, in data
    raise SMTPDataError(code, repl)
smtplib.SMTPDataError: (250, b'2.0.0 OK  1599418016 g192sm5199261pfb.168 - gsmtp')
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:16:56] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:18:48] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:19:14] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:27:45] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:27:45] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:31:30] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:31:30] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:31:59] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:32:52] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:32:52] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:33:16] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:35:36] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:35:36] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:37:07] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:37:07] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:38:23] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:38:23] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\ketan\Downloads\certificate_generator-master\app.py", line 57, in upload_files
    send_mail(name, email)
  File "c:\Users\ketan\Downloads\certificate_generator-master\app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 882, in sendmail
    (code, resp) = self.data(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 560, in data
    raise SMTPDataError(code, repl)
smtplib.SMTPDataError: (250, b'2.0.0 OK  1599419332 k88sm10599876pjk.19 - gsmtp')
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:38:52] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:44:06] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:44:06] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:44:30] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:46:18] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:46:18] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:46:47] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:48:46] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:48:46] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:49:05] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 00:49:15] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:41:13] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:41:13] "[33mGET /sun.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:41:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:41:47] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:41:58] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:42:20] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:42:20] "[33mGET /sun.jpg HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [07/Sep/2020 13:42:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 11:36:19] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 11:36:19] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 11:36:19] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 11:36:51] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:03:57] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:03:57] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:03:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:04:16] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:14:17] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:14:17] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:14:32] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:16:04] "[33mGET /templates/ HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:16:08] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:16:08] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:16:26] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:20:58] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:20:58] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:21:15] "[37mPOST /upload HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:31:44] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:31:44] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\smtplib.py", line 387, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "C:\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Python\Python37\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python\Python37\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 535, in mail
    return self.getreply()
  File "C:\Python\Python37\lib\smtplib.py", line 391, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:32:17] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:35:35] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:35:35] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "C:\Python\Python37\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Python\Python37\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:35:53] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:35:59] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:35:59] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:39] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:39] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:40] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:40] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:40] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:40] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:41] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:41] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "C:\Python\Python37\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Python\Python37\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:36:53] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "C:\Python\Python37\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Python\Python37\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:39:47] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:39:51] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:39:51] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:39:51] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:39:51] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "C:\Python\Python37\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Python\Python37\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:40:02] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:44:29] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:44:29] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "C:\Python\Python37\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Python\Python37\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:44:41] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "C:\Python\Python37\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Python\Python37\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:49:52] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:49:54] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:49:54] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:49:54] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:49:54] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 46, in upload_files
    dataframe = pandas.read_csv(data_file)
  File "C:\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Python\Python37\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:49:58] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:50:14] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:50:14] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 57, in upload_files
    send_mail(name, email)
  File "app.py", line 37, in send_mail
    server.send_message(msg)
  File "C:\Python\Python37\lib\smtplib.py", line 967, in send_message
    rcpt_options)
  File "C:\Python\Python37\lib\smtplib.py", line 861, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "C:\Python\Python37\lib\smtplib.py", line 534, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "C:\Python\Python37\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Python\Python37\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:50:28] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5500/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:55:05] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:55:06] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Sep/2020 12:55:21] "[37mPOST /upload HTTP/1.1[0m" 200 -
